---
name: CI
on: push

permissions:
  contents: read

jobs:
  release-please:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: jimeh/release-please-manifest-action@v2
